//
//  AvatarDraw.swift
//  Glider
//
//  Created by Yancen Li on 2/24/17.
//  Copyright © 2017 org.yancen. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

import UIKit

public class AvatarDraw : NSObject {
  
  //// Drawing Methods
  
  public dynamic class func drawAvatar(frame: CGRect = CGRect(x: 0, y: 0, width: 40, height: 40), userName: String = "H") {
    //// General Declarations
    let context = UIGraphicsGetCurrentContext()!
    
    //// Color Declarations
    let color = UIColor(red:1.00, green:0.40, blue:0.00, alpha:1.0)
    
    //// Avatar Border Drawing
    let avatarBorderRect = CGRect(x: frame.minX + 1, y: frame.minY + 1, width: 38, height: 38)
    let avatarBorderPath = UIBezierPath(ovalIn: avatarBorderRect)
    color.setFill()
    avatarBorderPath.fill()
    let avatarBorderStyle = NSMutableParagraphStyle()
    avatarBorderStyle.alignment = .center
    let avatarBorderFontAttributes = [NSFontAttributeName: UIFont(name: "AvenirNext-Regular", size: 20)!, NSForegroundColorAttributeName: UIColor.white, NSParagraphStyleAttributeName: avatarBorderStyle]
    
    let avatarBorderTextHeight: CGFloat = userName.boundingRect(with: CGSize(width: avatarBorderRect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: avatarBorderFontAttributes, context: nil).height
    context.saveGState()
    context.clip(to: avatarBorderRect)
    userName.draw(in: CGRect(x: avatarBorderRect.minX, y: avatarBorderRect.minY + (avatarBorderRect.height - avatarBorderTextHeight) / 2, width: avatarBorderRect.width, height: avatarBorderTextHeight), withAttributes: avatarBorderFontAttributes)
    context.restoreGState()
  }
  
}
